package be.ae.rest;

import be.ae.rest.model.Account;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import javax.validation.Valid;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;


/**
 * No description
 * (Generated with springmvc-raml-parser v.0.10.2)
 *
 */
@RestController
@RequestMapping("/api/accounts")
public class AccountController {

    /**
     * Get list of accounts
     *
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    public ResponseEntity<List<be.ae.rest.model.Account>> getAccounts() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Create new account
     *
     */
    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseEntity<?> createAccount(@Valid @RequestBody be.ae.rest.model.Account account) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Retrieve account details
     *
     */
    @RequestMapping(value = "/{accountId}", method = RequestMethod.GET)
    public be.ae.rest.model.Account getAccountById(@PathVariable String accountId) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Delete account
     *
     */
    @RequestMapping(value = "/{accountId}", method = RequestMethod.DELETE)
    public ResponseEntity<?> deleteAccountById(@PathVariable String accountId) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }
}